#postgres server is visible as pgsql-server in pgadmin panel

version: "3.5"
services:
  postgres:
    container_name: postgres_dogoo
    image: postgres
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "dogoo"
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_dogoo
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 123@test.pl
      PGADMIN_DEFAULT_PASSWORD: '123'
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "8080:80"
    restart: unless-stopped
    links:
      - "postgres:pgsql-server"

volumes:
    postgres:
    pgadmin: