version: "3"
services:
  postgres:
    container_name: postgres_playr
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "playr"